// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getdes
Rcpp::List getdes(arma::mat Ymat, arma::mat Vm1mat, arma::mat Vmat, arma::mat phix, arma::mat phiy, arma::mat Phil, int t0);
RcppExport SEXP _dynamo_getdes(SEXP YmatSEXP, SEXP Vm1matSEXP, SEXP VmatSEXP, SEXP phixSEXP, SEXP phiySEXP, SEXP PhilSEXP, SEXP t0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Ymat(YmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vm1mat(Vm1matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Vmat(VmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phix(phixSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phiy(phiySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phil(PhilSEXP);
    Rcpp::traits::input_parameter< int >::type t0(t0SEXP);
    rcpp_result_gen = Rcpp::wrap(getdes(Ymat, Vm1mat, Vmat, phix, phiy, Phil, t0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynamo_getdes", (DL_FUNC) &_dynamo_getdes, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynamo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
