# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getdes <- function(Ymat, Vm1mat, Vmat, phix, phiy, Phil, t0) {
    .Call(`_dynamo_getdes`, Ymat, Vm1mat, Vmat, phix, phiy, Phil, t0)
}

